name: Record Service CI

on:
  push:
    paths:
      - "services/record-service/**"
      - ".github/workflows/record-ci.yml"
  pull_request:
    paths:
      - "services/record-service/**"

jobs:
  build-test:
    name: Build & Test Record Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('services/record-service/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build & run tests
        working-directory: services/record-service
        run: mvn clean verify
