spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/phr-config-repo.git
          default-label: main
  application:
    name: config-service

management:
  endpoints:
    web:
      exposure: health,info,env,configprops
