# Override defaults from prometheus-community/prometheus
alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  global:
    scrape_interval: 15s
  service:
    type: ClusterIP
    port: 9090
  ingress:
    enabled: false
  extraScrapeConfigs: |
    - job_name: 'phr-services'
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names: ['phr-system']
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: (.+):\d+;(\d+)
          replacement: $1:$2
          target_label: __address__
