spring:
  profiles:
    active: ${PROFILE:dev}
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
        - id: record
          uri: http://record-service:8081
          predicates:
            - Path=/api/records/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
