# Override defaults from grafana chart
adminUser: admin
adminPassword: secret_password  # override via Helm --set or sealed secret in prod
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  # annotations:
  #   kubernetes.io/ingress.class: nginx
plugins:
  - grafana-piechart-panel
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        folder: ''
        type: file
        options:
          path: /var/lib/grafana/dashboards
dashboards:
  health-record-dashboard:
    json: |-
      {{ .Files.Get "dashboards/health-record-dashboard.json" }}
  infra-dashboard:
    json: |-
      {{ .Files.Get "dashboards/infra-dashboard.json" }}
